// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID        string `json:"id"`
	Qty       int32  `json:"qty"`
	ProductID string `json:"productId"`
	EventID   string `json:"eventId"`
	CreatedAt string `json:"createdAt"`
	Price     int32  `json:"price"`
}

type Query struct {
}

type Subscription struct {
}
