apiVersion: batch/v1
kind: Job
metadata:
  name: pg-migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  # fail the Job if it runs longer than 5 minutes and limit retries
  activeDeadlineSeconds: 300
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: bitnami/postgresql:17
          command: ["/bin/sh","-c"]
          args:
            - >-
              PGPASSWORD=${PGPASSWORD} \
              PGCONNECT_TIMEOUT=${PGCONNECT_TIMEOUT:-10} \
              psql -h ${PGHOST} -U ${PGUSER} -d ${PGDATABASE} -v ON_ERROR_STOP=1 -f /sql/migrate.sql;
          env:
            - name: PGHOST
              value: {{ .Values.postgres.host | quote }}
            - name: PGUSER
              value: {{ .Values.postgres.user | quote }}
            - name: PGPASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgres.db | quote }}
            - name: PGCONNECT_TIMEOUT
              value: "10"
          volumeMounts:
            - name: sql
              mountPath: /sql
      volumes:
        - name: sql
          configMap:
            name: pg-init-sql
            items: [{ key: migrate.sql, path: migrate.sql }] 
