apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-index
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongosh
          image: bitnami/mongodb:7.0
          command: ["/bin/bash","-c"]
          args:
            - >-
              mongosh "${MONGO_URI}" --eval 'db.orders.createIndex({eventId:1},{unique:true})';
          env:
            - name: MONGO_URI
              value: {{ .Values.mongo.uri | quote }}
