apiVersion: batch/v1
kind: Job
metadata:
  name: pg-seed
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: bitnami/postgresql:16
          command: ["/bin/sh","-c"]
          args:
            - >-
              PGPASSWORD=${PGPASSWORD} psql -h ${PGHOST} -U ${PGUSER} -d ${PGDATABASE} -f /sql/seed.sql;
          env:
            - name: PGHOST
              value: {{ .Values.postgres.host | quote }}
            - name: PGUSER
              value: {{ .Values.postgres.user | quote }}
            - name: PGPASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgres.db | quote }}
          volumeMounts:
            - name: sql
              mountPath: /sql
      volumes:
        - name: sql
          configMap:
            name: pg-init-sql
            items: [{ key: seed.sql, path: seed.sql }]
