stages: [lint, test, build]

golang-lint:
  stage: lint
  image: golang:1.22
  script:
    - cd services/productsvc && go vet ./...
    - cd ../ordersvc && go vet ./...

go-test:
  stage: test
  image: golang:1.22
  script:
    - cd services/productsvc && go test ./... || true
    - cd ../ordersvc && go test ./... || true

docker-build-product:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile services/productsvc/Dockerfile --destination $CI_REGISTRY_IMAGE/productsvc:${CI_COMMIT_SHORT_SHA}

docker-build-order:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile services/ordersvc/Dockerfile --destination $CI_REGISTRY_IMAGE/ordersvc:${CI_COMMIT_SHORT_SHA}
