apiVersion: v2
name: frontend
version: 0.1.0
appVersion: "0.1.0"
# dependencies:
#   - name: product-svc
#     version: 0.1.0
#     repository: "file://../product-svc"
#   - name: order-svc
#     version: 0.1.0
#     repository: "file://../order-svc"