image:
  repository: registry.infra.svc.cluster.local/frontend
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 3000
  type: ClusterIP
env:
  GRAPHQL_URL: http://productsvc.app.svc.cluster.local/graphql
