image:
  repository: frontend
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 3000
  type: ClusterIP
env:
  GRAPHQL_URL: http://product-svc.app.svc.cluster.local/graphql
