apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: "{{ .Values.image }}"
          args:
            - "start"
            - "--uri"
            - "file:/etc/flagd/flags.json"
          ports:
            - containerPort: 8013
          volumeMounts:
            - name: flags
              mountPath: /etc/flagd
              readOnly: true
      volumes:
        - name: flags
          configMap:
            name: flagd-config
            items:
              - key: "flags.json"
                path: "flags.json"
