
services:

  nats:
    image: nats:2.10-alpine
    ports: ["4222:4222", "8222:8222"]

  postgres:
    image: bitnamisecure/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app
      - POSTGRESQL_DATABASE=app
    ports: ["5432:5432"]

  mongo:
    image: bitnamisecure/mongodb:latest
    ports: ["27017:27017"]

  redis:
    image: bitnamisecure/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: ["6379:6379"]

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    command: ["start", "--uri", "file:/etc/flagd/flags.json"]
    volumes:
      - ./flagd/flags.json:/etc/flagd/flags.json:ro
    ports: ["8013:8013"]

  productsvc:
    build:
      context: ..
      dockerfile: services/productsvc/Dockerfile
    restart: always
    environment:
      - AUTO_MIGRATE=true
      - DATABASE_URL=postgres://app:app@postgres:5432/app?sslmode=disable
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - LOG_LEVEL=debug
      - NATS_URL=nats://nats:4222
      - REDIS_ADDR=redis:6379
      - BUILD_VERSION=${BUILD_VERSION:-dev}
    depends_on: [postgres, redis, nats, flagd]
    ports: ["8080:8080"]

  ordersvc:
    build:
      context: ..
      dockerfile: services/ordersvc/Dockerfile
    restart: always
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - LOG_LEVEL=debug
      - MONGO_URI=mongodb://mongo:27017
      - NATS_URL=nats://nats:4222
    depends_on: [mongo, nats, flagd]
    ports: ["8081:8081"]
