// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID        string `json:"id"`
	ProductID string `json:"productId"`
	Qty       int32  `json:"qty"`
	CreatedAt string `json:"createdAt"`
}

type Product struct {
	ID    string `json:"id"`
	Price int32  `json:"price"`
	Name  string `json:"name"`
}

type Query struct {
}

type Subscription struct {
}

type Time struct {
	UnixTime  int32  `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
