package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"encoding/json"
	"fmt"
	rand "math/rand/v2"
	"rxw1/logging"
	"rxw1/ordersvc/internal/model"
	"time"

	nats "github.com/nats-io/nats.go"
	ulid "github.com/oklog/ulid/v2"
)

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CancelOrder - cancelOrder"))
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, productID string, qty int32) (*model.Order, error) {
	ctx = logging.With(ctx, "productID", productID)
	logging.From(ctx).Info("[mutationResolver] CreateOrder")

	event := map[string]any{
		"id":        ulid.Make().String(),
		"eventID":   ulid.Make().String(),
		"productID": productID,
		"qty":       qty,
		"createdAt": time.Now().UTC().Format(time.RFC3339),
	}

	b, err := json.Marshal(event)
	if err != nil {
		logging.From(ctx).Error("failed to marshal event", "error", err)
		return nil, err
	}

	time.Sleep(time.Duration(rand.IntN(500)) * time.Millisecond)

	if err := r.NC.Publish("order.created", b); err != nil {
		logging.From(ctx).Error("failed to publish event", "error", err)
		return nil, err
	}

	order := &model.Order{
		ID:        event["id"].(string),
		Qty:       event["qty"].(int32),
		ProductID: event["productID"].(string),
		EventID:   event["eventID"].(string),
		CreatedAt: event["createdAt"].(string),
	}

	logging.From(ctx).Info("order created", "order", order)
	return order, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	ctx = logging.With(ctx)
	logging.From(ctx).Info("[queryResolver] Orders")

	msg, err := r.NC.Request("orders.all", nil, 2*time.Second)
	if err != nil {
		logging.From(ctx).Error("failed to request orders", "subject", "orders.all", "error", err)
		return nil, err
	}

	var orders []*model.Order
	if err := json.Unmarshal(msg.Data, &orders); err != nil {
		logging.From(ctx).Error("failed to unmarshal orders", "error", err)
		return nil, err
	}

	logging.From(ctx).Info("fetched orders", "count", len(orders))
	return orders, nil
}

// OrdersByUserID is the resolver for the ordersByUserId field.
func (r *queryResolver) OrdersByUserID(ctx context.Context, userID string) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: OrdersByUserID - ordersByUserId"))
}

// OrderByID is the resolver for the orderById field.
func (r *queryResolver) OrderByID(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: OrderByID - orderById"))
}

// LastOrderCreated is the resolver for the lastOrderCreated field.
func (r *subscriptionResolver) LastOrderCreated(ctx context.Context) (<-chan *model.Order, error) {
	ctx = logging.With(ctx)
	logging.From(ctx).Info("[subscriptionResolver] LastOrderCreated")
	ch := make(chan *model.Order, 8) // buffered to avoid blocking NATS callback

	sub, err := r.NC.Subscribe("order.created", func(m *nats.Msg) {
		var o model.Order
		if err := json.Unmarshal(m.Data, &o); err != nil {
			logging.From(ctx).Error("failed to unmarshal order", "error", err)
			return
		}
		select {
		case ch <- &o:
		case <-ctx.Done():
			return
		}
	})
	if err != nil {
		return nil, err
	}

	go func() {
		<-ctx.Done()
		_ = sub.Unsubscribe()
		close(ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
