apiVersion: v2
name: registry
version: 0.1.0
icon: https://raw.githubusercontent.com/open-feature/artwork/main/brand/open-feature-logo.png
description: A Helm chart for flagd, the OpenFeature flag evaluation service
appVersion: "latest"
