name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-services:
    name: Go services (build & test)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - services/productsvc
          - services/ordersvc
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Go build
        run: go build ./...

      - name: Go test
        run: go test ./...

  frontend:
    name: Frontend (build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/frontend/package-lock.json

      - name: Install deps
        run: npm ci

      # Codegen reads from NEXT_PUBLIC_GRAPHQL_URL; we skip codegen here and rely on committed generated files.
      - name: Build
        run: npm run build

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [go-services, frontend]
    steps:
      - run: echo "CI completed for Go services and frontend."
