name: E2E

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'infra/**'
      - 'services/**'
      - 'tests/e2e/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images (compose)
        run: |
          docker compose -f infra/compose.dev.yml build

      - name: Start stack
        run: |
          docker compose -f infra/compose.dev.yml up -d

      - name: Wait for services
        run: |
          tries=60
          until curl -sf http://localhost:8080/ >/dev/null; do echo "waiting productsvc"; sleep 2; tries=$((tries-1)); test $tries -gt 0 || exit 1; done
          tries=60
          until curl -sf http://localhost:8081/healthz >/dev/null; do echo "waiting ordersvc"; sleep 2; tries=$((tries-1)); test $tries -gt 0 || exit 1; done

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Run e2e tests
        working-directory: tests/e2e
        run: go test -v ./...

      - name: Diagnostics on failure
        if: failure()
        run: |
          docker compose -f infra/compose.dev.yml ps
          docker compose -f infra/compose.dev.yml logs --no-color --tail=200

      - name: Teardown
        if: always()
        run: docker compose -f infra/compose.dev.yml down -v
